info:
  build:
    artifact: political-actor-recommendation-system
    name: political-actor-recommendation-system
    description: political-actor-recommendation-system
    version: '@project.version@'

management:
  port: 3233
  security:
    enabled: false

server:
  port: 2233
  
security:
  user:
    password: null
  basic:
    enabled: false
  

spring:
  profiles:
  
  redis:
    host: localhost
    port: 6379
    database: 0
  
  kafka:
    bootstrap-servers:
    - localhost:9092
    consumer:
      auto-offset-reset: earliest
      group-id: politicalActorRecommendation
      enable-auto-commit: false
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      
    producer:
      batch-size: 16384
      buffer-memory: 33554432
      retries: 0
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

app:
  properties:
#    newsApiUrl: https://newsapi.org/v1/articles
#    newsApiKey: 65389fbdb76e4955874a20a715ee380e  
    newsApiUrl: https://api.nytimes.com/svc/news/v3/content/all/
    newsApiKey: fd184ced33294fda93d5274c3b3b7004
    newsApisource: u.s.
    
    jaccardDistanceThreshold: 0.70
    cameoToRedisAdd: false
    addNewActorAutomatic: false
    maximumNoOfActorDiscovery: 2
    redisCameoKey: psa.actor.dictionary
    redisOutputKey: psa.output.newActor
    
    kafka:
      topic: par.topic
      messageKey: par.key
      zookeeperAddress: localhost:2181
  
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    com.par.system: DEBUG 
